coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 50%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - dev
          - main